#
# Module manifest for module 'xo-powershell'
#
# Generated by: Vates
#
# Generated on: 4/20/2026
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'xo-powershell.psm1'

    # Version number of this module.
    ModuleVersion        = '1.0.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID                 = 'adaf591c-6abd-4084-89f9-d75a9096743d'

    # Author of this module
    Author               = 'Vates'

    # Company or vendor of this module
    CompanyName          = 'Vates'

    # Copyright statement for this module
    Copyright            = 'Copyright (c) Vates.'

    # Description of the functionality provided by this module
    Description          = 'Xen Orchestra PowerShell module'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '7.0'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules      = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess     = @(
        "formats/sr.ps1xml"
        "formats/task.ps1xml"
        "formats/vdi.ps1xml"
        "formats/vm.ps1xml"
        "formats/vdi-snapshot.ps1xml"
        "formats/vm-snapshot.ps1xml"
        "formats/server.ps1xml"
        "formats/host.ps1xml"
        "formats/pool.ps1xml"
        "formats/pool-patch.ps1xml"
        "formats/message.ps1xml"
        "formats/network.ps1xml"
        "formats/pif.ps1xml"
        "formats/vif.ps1xml"
        "formats/vbd.ps1xml"
        "formats/alarm.ps1xml"
        "formats/schedule.ps1xml"
        "formats/vm-template.ps1xml"
        "formats/backup-job.ps1xml"
        "formats/backup-archive.ps1xml"
        "formats/backup-log.ps1xml"
        "formats/backup-repository.ps1xml"
        "formats/dashboard.ps1xml"
        "formats/event.ps1xml"
        "formats/group.ps1xml"
        "formats/pbd.ps1xml"
        "formats/pci.ps1xml"
        "formats/pgpu.ps1xml"
        "formats/proxy.ps1xml"
        "formats/restore-log.ps1xml"
        "formats/sm.ps1xml"
        "formats/user.ps1xml"
        "formats/user-authentication-token.ps1xml"
        "formats/vm-controller.ps1xml"
    )

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = @()

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Variables to export from this module
    VariablesToExport    = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @(
        "Connect-XenOrchestra"
        "Disconnect-XenOrchestra"
        # task
        "Get-XoTaskDetails"
    )

    # DSC resources to export from this module
    DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{
        PSData = @{
            LicenseUri   = 'https://spdx.org/licenses/Apache-2.0.html'
            ProjectUri   = 'https://github.com/vatesfr/xo-powershell'
            Prerelease   = 'beta'
            ReleaseNotes = ''
        }
    }

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
